name: Scan Main On Push

on:
  push:
    branches: [ main ]

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: Install dependencies
      # https://github.com/conda-incubator/setup-miniconda
      uses: conda-incubator/setup-miniconda@3b0f2504dd76ef23b6d31f291f4913fb60ab5ff3 # v2
      with:
        channels: default,conda-forge,joshburt
        auto-activate-base: true
        activate-environment: github.action
        environment-file: environment.github.yml
    - name: Conda Info
      run: |
        conda info
    - name: Anaconda Project Setup
      env:
        MLFLOW_TRACKING_ENTITY_TTL: FAKE-TRACKING-ENTITY-TTL
        MLFLOW_TRACKING_GC_TTL: FAKE-TRACKING-GC-TTL
        MLFLOW_ARTIFACTS_DESTINATION: FAKE-ARTIFACTS-DESTINATION
        MLFLOW_BACKEND_STORE_URI: FAKE-BACKEND-STORE-URI
        AE_AUTH: FAKE-AUTH
        AE_USERNAME: FAKE-USERNAME
        AE_HOSTNAME: FAKE-HOST
      run: |
        anaconda-project prepare --env-spec default --mode development_defaults
    - name: Linting
      run: |
        anaconda-project run lint
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
